jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Download Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./build/test

name: Verify

on:
  schedule:
    - cron: "35 */6 * * *"
